### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by akb0787** [Eric-mingjie/network-slimming#14]
hey Eric. i got this error during pruning , can you suggest me how should i handle it. Thanks

Traceback (most recent call last):
  File "vggprune.py", line 128, in <module>
    newmodel = vgg(cfg=cfg)
  File "/home/ustc/akb/network-slimming/models/vgg.py", line 22, in __init__
    self.feature = self.make_layers(cfg, True)
  File "/home/ustc/akb/network-slimming/models/vgg.py", line 39, in make_layers
    conv2d = nn.Conv2d(in_channels, v, kernel_size=3, padding=1, bias=False)
  File "/home/ustc/anaconda2/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 297, in __init__
    False, _pair(0), groups, bias)
  File "/home/ustc/anaconda2/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 38, in __init__
    self.reset_parameters()
  File "/home/ustc/anaconda2/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 44, in reset_parameters
    stdv = 1. / math.sqrt(n)
ZeroDivisionError: float division by zero

**Comment by Eric-mingjie** [comment]
Which prune ratio are you using? This could happen if you set prune ratio to be large where some layers could get zero channels left.

**Comment by akb0787** [comment]
i am using default ratio of 0.7 on cifar10 for vgg19.

**Comment by Eric-mingjie** [comment]
Did your train your vgg model with sparsity?

**Comment by akb0787** [comment]
yes i did, and i varied prune ratio but no effect.

**Comment by Eric-mingjie** [comment]
So you try prune ratio less than 0.7 and still does not work? Maybe you can train a second vgg model and see if it still does not work.
